### ISSUE TITLE
Compile issue against Varnish 4.0.3

### ISSUE THREAD

**Issue by tjursonovics** [varnish/libvmod-digest#14]
Hi there,

I tried to compile against varnish 4.0.3 (which is more stable in my view than 4.1), but I got an issue:

```bash
cdn@da-pm01:~/libvmod-digest$ make
make  all-recursive
make[1]: Entering directory `/home/cdn/libvmod-digest'
Making all in src
make[2]: Entering directory `/home/cdn/libvmod-digest/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c -o vmod_digest.lo vmod_digest.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c:91:53: warning: 'enum vcl_event_e' declared inside parameter list [enabled by default]
 init_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
                                                     ^
vmod_digest.c:91:53: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
vmod_digest.c:91:65: error: parameter 3 ('e') has incomplete type
 init_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
                                                                 ^
```

Could you please check it?

KR
Tamás

**Comment by tjursonovics** [comment]
I have found the root cause: in varnish 4.0, the declaration of vcl_event_e is missing. Does libvmod-digest support V4.0.3?


vcl.h (4.0.3):
```c
/*
 * NB:  This file is machine generated, DO NOT EDIT!
 *
 * Edit and run generate.py instead
 */

struct vrt_ctx;
#define VRT_CTX const struct vrt_ctx *ctx
struct req;
struct busyobj;
struct ws;
struct cli;
struct worker;

typedef int vcl_init_f(struct cli *);
typedef void vcl_fini_f(struct cli *);
typedef int vcl_func_f(VRT_CTX);
```

**Comment by fgsch** [comment]
Are you using the 4.0 branch?

**Comment by gquintard** [comment]
Hi,
Dumb question: are you using the right branch (4.0)?

**Comment by Francois-v3** [comment]
Hi,

Yep. Just use branch 4.0 instead of master.

François V.

Le 08/02/2016 19:12, Tamás Jursonovics a écrit :
>
> I have found the root cause: in varnish 4.0, the declaration of 
> vcl_event_e is missing. Does libvmod-digest support V4.0.3?
>
> vcl.h (4.0.3):
>
> /*
> * NB: This file is machine generated, DO NOT EDIT!
> *
> * Edit and run generate.py instead
> */
>
> struct  vrt_ctx;
> #define  VRT_CTX  const  struct  vrt_ctx *ctx
> struct  req;
> struct  busyobj;
> struct  ws;
> struct  cli;
> struct  worker;
>
> typedef  int  vcl_init_f(struct  cli *);
> typedef  void  vcl_fini_f(struct  cli *);
> typedef  int  vcl_func_f(VRT_CTX);
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/varnish/libvmod-digest/issues/14#issuecomment-181442707>.
>

-- 
François Veux - +33633267508

**Comment by tjursonovics** [comment]
Yes, indeed, I was using the wrong branch...
