### ISSUE TITLE
Don't work digest.base64_decode

### ISSUE THREAD

**Issue by SeniorCoder1025** [varnish/libvmod-digest#17]
I've tried to use digest.base64_decode in default.vcl, but not work.
set req.http.x-url = digest.base64_decode("dGVzdHVybA==");
But x-url is empty.
And when use base64(), it's crashed.
Please let me know what I mistake in the code.

**Comment by rezan** [comment]
Not able to replicate this. What version of Varnish? How did you install it and this vmod?

**Comment by SeniorCoder1025** [comment]
I've used Varnish 4.1.1 and installed on ubuntu 14.04 using apt-get install, after register the repository of varnish.
After install varnish devapi, I was able to install the digest through compiling the source.
But the base64 decode doesn't work.

**Comment by rezan** [comment]
Can you gist your VCL and the varnishlog output for the request?

**Comment by rezan** [comment]
No way to replicate. Please feel free to re-open.
