### ISSUE TITLE
Compile issue on CentOS 7

### ISSUE THREAD

**Issue by stevenmunro** [varnish/libvmod-digest#19]
./autogen.sh runs fine
./configure runs fine
make gives me the following. Sorry I'm sure where to begin troubleshooting this.

```
[root@ip-xxx-xxx-xxx-xxx libvmod-digest]# make
make  all-recursive
make[1]: Entering directory `/root/libvmod-digest'
Making all in src
make[2]: Entering directory `/root/libvmod-digest/src'
/usr/share/varnish/vmodtool.py ../src/vmod_digest.vcc
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c -o vmod_digest.lo vmod_digest.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c:95:53: warning: 'enum vcl_event_e' declared inside parameter list [enabled by default]
 init_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
                                                     ^
vmod_digest.c:95:53: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
vmod_digest.c:95:65: error: parameter 3 ('e') has incomplete type
 init_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
                                                                 ^
vmod_digest.c: In function 'init_function':
vmod_digest.c:100:11: error: 'VCL_EVENT_LOAD' undeclared (first use in this function)
  if (e != VCL_EVENT_LOAD)
           ^
vmod_digest.c:100:11: note: each undeclared identifier is reported only once for each function it appears in
vmod_digest.c:95:65: warning: unused parameter 'e' [-Wunused-parameter]
 init_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
                                                                 ^
make[2]: *** [vmod_digest.lo] Error 1
make[2]: Leaving directory `/root/libvmod-digest/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/libvmod-digest'
make: *** [all] Error 2
```

**Comment by fgsch** [comment]
Which branch are you using and what varnish version?

**Comment by stevenmunro** [comment]
I am using Varnish 4.0.3 and I am using the master branch

**Comment by fgsch** [comment]
Please try with the 4.0 branch instead. Master tracks 4.1.

**Comment by stevenmunro** [comment]
Thanks for your very prompt response, I will give that a go now

**Comment by stevenmunro** [comment]
I am getting different errors now.

`[root@ip-172-31-11-180 libvmod-digest]# make
make  all-recursive
make[1]: Entering directory `/root/libvmod-digest'
Making all in src
make[2]: Entering directory `/root/libvmod-digest/src'
/usr/share/varnish/vmodtool.py ../src/vmod_digest.vcc
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c -o vmod_digest.lo vmod_digest.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c: In function 'vmod_hmac_generic':
vmod_digest.c:280:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (j = 0; j < blocksize; j++) {
                ^
In file included from /usr/include/varnish/common/common.h:37:0,
                 from /usr/include/varnish/cache/cache.h:37,
                 from vmod_digest.c:55:
vmod_digest.c:283:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   assert((hexptr-hexenc)<(2*blocksize + 3));
                         ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_digest.c: In function 'vmod_hash_generic':
vmod_digest.c:351:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i<mhash_get_block_size(hash);i++) {
               ^
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c -o vmod_digest.o >/dev/null 2>&1
mv -f .deps/vmod_digest.Tpo .deps/vmod_digest.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c -o vcc_if.lo vcc_if.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c  -fPIC -DPIC -o .libs/vcc_if.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c -o vcc_if.o >/dev/null 2>&1
mv -f .deps/vcc_if.Tpo .deps/vcc_if.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -O2 -module -export-dynamic -avoid-version -shared -lmhash  -o libvmod_digest.la -rpath /usr/lib64/varnish/vmods vmod_digest.lo vcc_if.lo
libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  .libs/vmod_digest.o .libs/vcc_if.o   -lmhash  -O2   -Wl,-soname -Wl,libvmod_digest.so -o .libs/libvmod_digest.so
libtool: link: ( cd ".libs" && rm -f "libvmod_digest.la" && ln -s "../libvmod_digest.la" "libvmod_digest.la" )
make[2]: Leaving directory `/root/libvmod-digest/src'
make[2]: Entering directory `/root/libvmod-digest'
========================================
You need rst2man installed to make dist
========================================
make[2]: *** [vmod_digest.3] Error 1
make[2]: Leaving directory `/root/libvmod-digest'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/libvmod-digest'
make: *** [all] Error 2`

**Comment by fgsch** [comment]
You need to install python-docutils.

**Comment by stevenmunro** [comment]
Yes I installed that, I was able to compile /libvmod-cookie
It still shows the 3 warnings as above, however was able to install vmod using make install.

**Comment by Dridi** [comment]
Thank you for your report, I have turned warning into errors from now on, but those look harmless.

**Comment by fgsch** [comment]
@stevenmunro: do you mean this vmod built once you installed python-docutils? You are mentioning libvmod-cookie. I'm a bit confused.

**Comment by stevenmunro** [comment]
Ahh yes. When I tried to install libvmod-cookie, the *only* error on that particular compile was needing python-docutils. So once I had that installed, the compile for libvmod-cookie was successful.

When you mentioned I needed python-docutils, I knew I already had it so I gave the compile another go and hence it worked. However just those 3 warnings, as you mentioned they look harmless.

**Comment by fgsch** [comment]
@stevenmunro thanks for clarifying.

@Dridi how is turning the warnings into an error helping?

**Comment by rezan** [comment]
The warnings were fixed in master only:

https://github.com/varnish/libvmod-digest/commit/50289d9729ea7155f82a9cc3a4a89295006a9c8d

**Comment by Dridi** [comment]
It appears I managed to push commits in master (f0121a8) and 4.0 (6ea7b8d) during this morning's short blackout on github. I expected them to show up in this ticket since I reference it in both but they don't appear in the branches in the web ui. A git push tells me that the branches are up to date.

Can someone please have a look?

**Comment by fgsch** [comment]
Indeed. Time to ping github support I guess.

**Comment by fgsch** [comment]
This should be fixed and the commits are showing now.
Please reopen this ticket if you are still having issues.
