### ISSUE TITLE
centos 6.4 compile error due to dependency

### ISSUE THREAD

**Issue by mliu5715k** [varnish/libvmod-digest#21]
I'd like to use this vmod but am not familiar with compiling c code.
"./configure" fails with this error 
```
checking for mhash_count in -lmhash... no
configure: error: libvmod-digest requires libmhash.
```
i have the libmhash rpm and the .so files in my system, do I just need to "link" to the libmhash or copy them to certain dir and re-run configure?.
``` 
mhash-0.9.9.9-3.el6.x86_64
-rwxr-xr-x 1 root root 180808 Jul  8  2010 /usr/lib64/libmhash.so.2.0.1
```

**Comment by mliu5715k** [comment]
figured it out, had to install the "devel" version of the "mhash" package "mhash-devel-0.9.9-2.3.x86_64.rpm" that contains the header file and the .rc file needed for compiling.

**Comment by pbodsk** [comment]
Just a follow up.

I had the same problem when trying to compile this module on macOS. 

The solution, as described in #10 was to set the `LDFLAGS` and `CPPFLAGS` like so:

`env LDFLAGS="-L/usr/local/lib" CPPFLAGS="-I/usr/local/include" ./configure`
