### ISSUE TITLE
Compile broken on FreeBSD

### ISSUE THREAD

**Issue by michbsd** [varnish/libvmod-digest#28]
The latest commit to src/vmod_digest.c seems to have broken compile on FreeBSD

libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include/varnish -Wall -Wextra -Werror -I/usr/local/include -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:186:1: error: "PACKAGE" redefined
In file included from vmod_digest.c:34:
../config.h:50:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:189:1: error: "PACKAGE_BUGREPORT" redefined
In file included from vmod_digest.c:34:
../config.h:53:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:192:1: error: "PACKAGE_NAME" redefined
In file included from vmod_digest.c:34:
../config.h:56:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:195:1: error: "PACKAGE_STRING" redefined
In file included from vmod_digest.c:34:
../config.h:59:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:198:1: error: "PACKAGE_TARNAME" redefined
In file included from vmod_digest.c:34:
../config.h:62:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:201:1: error: "PACKAGE_VERSION" redefined
In file included from vmod_digest.c:34:
../config.h:68:1: error: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from vmod_digest.c:45:
/usr/local/include/mutils/mhash_config.h:213:1: error: "VERSION" redefined
In file included from vmod_digest.c:34:

**Comment by daghf** [comment]
Preferably this should be fixed in freebsd's mhash packaging, which really should not include those defines in a published header file.

Is there any chance whoever is the Ports maintainer of mhash could be persuaded to fix this?

**Comment by michbsd** [comment]
https://www.freshports.org/security/mhash/

There is none :-/

**Comment by michbsd** [comment]
I will submit a PR to the ports team with a patch

**Comment by Dridi** [comment]
@michbsd, thank you for your help. I am responsible for breaking this and chose to do so because 1) that's a mhash "bug" as @daghf mentioned and 2) it was no longer needed on the platforms we support. Thanks again for helping fixing this on the FreeBSD side and it's a bit unfortunate that the mhash port has no active maintainer.

**Comment by michbsd** [comment]
I have just committed a fix to the ports tree that is fixing this - so I guess we can close this issue.

https://svnweb.freebsd.org/ports?view=revision&revision=466946
