### ISSUE TITLE
Unknown types in file included from vmod_digest

### ISSUE THREAD

**Issue by tmcevoy14** [varnish/libvmod-digest#31]
It seems that in the latest commit `c42b9fa62a4fba2d861d87b9699d9f591198249c` some change was made that is incompatible with Varnish v. **5.2.1**. 

**When I run the make install command on this latest version, I get the following error:**
`In file included from vmod_digest.c:53:0:\nvcc_if.h:12:1: error: unknown type name 'vmod_event_f'\n vmod_event_f event_function;\n ^\nvcc_if.h:14:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha256(VRT_CTX, VCL_STRING, VCL_STRING);\n ^\nvcc_if.h:14:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha256(VRT_CTX, VCL_STRING, VCL_STRING);\n                                      ^\nvcc_if.h:14:50: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha256(VRT_CTX, VCL_STRING, VCL_STRING);\n                                                  ^\nvcc_if.h:15:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha1(VRT_CTX, VCL_STRING, VCL_STRING);\n ^\nvcc_if.h:15:36: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha1(VRT_CTX, VCL_STRING, VCL_STRING);\n                                    ^\nvcc_if.h:15:48: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_sha1(VRT_CTX, VCL_STRING, VCL_STRING);\n                                                ^\nvcc_if.h:16:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_md5(VRT_CTX, VCL_STRING, VCL_STRING);\n ^\nvcc_if.h:16:35: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_md5(VRT_CTX, VCL_STRING, VCL_STRING);\n                                   ^\nvcc_if.h:16:47: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hmac_md5(VRT_CTX, VCL_STRING, VCL_STRING);\n                                               ^\nvcc_if.h:17:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:17:33: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64(VRT_CTX, VCL_STRING);\n                                 ^\nvcc_if.h:18:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64_hex(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:18:37: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64_hex(VRT_CTX, VCL_STRING);\n                                     ^\nvcc_if.h:19:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64_decode(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:19:40: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64_decode(VRT_CTX, VCL_STRING);\n                                        ^\nvcc_if.h:20:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:20:36: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url(VRT_CTX, VCL_STRING);\n                                    ^\nvcc_if.h:21:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_hex(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:21:40: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_hex(VRT_CTX, VCL_STRING);\n                                        ^\nvcc_if.h:22:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_decode(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:22:43: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_decode(VRT_CTX, VCL_STRING);\n                                           ^\nvcc_if.h:23:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:23:42: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad(VRT_CTX, VCL_STRING);\n                                          ^\nvcc_if.h:24:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad_hex(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:24:46: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad_hex(VRT_CTX, VCL_STRING);\n                                              ^\nvcc_if.h:25:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad_decode(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:25:49: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_base64url_nopad_decode(VRT_CTX, VCL_STRING);\n                                                 ^\nvcc_if.h:26:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha1(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:26:36: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha1(VRT_CTX, VCL_STRING);\n                                    ^\nvcc_if.h:27:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha224(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:27:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha224(VRT_CTX, VCL_STRING);\n                                      ^\nvcc_if.h:28:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha256(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:28:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha256(VRT_CTX, VCL_STRING);\n                                      ^\nvcc_if.h:29:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha384(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:29:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha384(VRT_CTX, VCL_STRING);\n                                      ^\nvcc_if.h:30:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha512(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:30:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_sha512(VRT_CTX, VCL_STRING);\n                                      ^\nvcc_if.h:31:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_gost(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:31:36: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_gost(VRT_CTX, VCL_STRING);\n                                    ^\nvcc_if.h:32:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md2(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:32:35: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md2(VRT_CTX, VCL_STRING);\n                                   ^\nvcc_if.h:33:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md4(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:33:35: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md4(VRT_CTX, VCL_STRING);\n                                   ^\nvcc_if.h:34:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md5(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:34:35: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_md5(VRT_CTX, VCL_STRING);\n                                   ^\nvcc_if.h:35:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_crc32(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:35:37: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_crc32(VRT_CTX, VCL_STRING);\n                                     ^\nvcc_if.h:36:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_crc32b(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:36:38: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_crc32b(VRT_CTX, VCL_STRING);\n                                      ^\nvcc_if.h:37:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_adler32(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:37:39: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_adler32(VRT_CTX, VCL_STRING);\n                                       ^\nvcc_if.h:38:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval128(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:38:40: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval128(VRT_CTX, VCL_STRING);\n                                        ^\nvcc_if.h:39:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval160(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:39:40: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval160(VRT_CTX, VCL_STRING);\n                                        ^\nvcc_if.h:40:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval192(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:40:40: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval192(VRT_CTX, VCL_STRING);\n                                        ^\nvcc_if.h:41:1: error: unknown type name 'VCL_STRING'\n VCL_STRING vmod_hash_haval224(VRT_CTX, VCL_STRING);\n ^\nvcc_if.h:41:40: error: unknown type name 'VCL_STRING'\n `

**But, when I run it on the previous sha** `4ca2b4713c57d5fe2c5525862e3dbeb02ae8d748` **it works successfully.**

**Comment by Dridi** [comment]
You should definitely upgrade to [Varnish 6.0 LTS](https://packagecloud.io/varnishcache/varnish60lts), the 5.2 series is not supported and has outstanding bugs that won't be fixed. The latest commit solves #29 (Varnish 6.2 support) and as of today the oldest supported Varnish release is 6.0 and we aren't planning to support older releases than that.
