### ISSUE TITLE
digest.base64 not working

### ISSUE THREAD

**Issue by irbasha** [varnish/libvmod-digest#34]
Hi,

I have compiled your digest module and trying to use base64 in my vcl but it fails. I have a vcl file say `mymodule.vcl` and it has very simple logic within a subroutine say initiate_request. This subroutine is called in my `main.vcl` file and it checks for a keyword in url and encodes the ip address when true else not. 
When i hit a request containing the keyword i see 502 error and varnish logs are also exiting. i see `log abandoned log reacquired` lines in the end.
Provided vcl file content and logs below. please provide us a solution and root cause of this issue.
my varnish version is 5.1.3
and i installed this module as instructed in readme file.
```
// mymodule.vcl
vcl 4.0;

import digest;

sub initiate_request {
    if (req.url ~ "/site1/") {
        set req.http.digest = digest.base64(client.ip);
    } else {
        set req.http.digest = client.ip;
    }
}
```
on hitting the url the logs are
```
*   << Session  >> 1         
-   Begin          sess 0 HTTP/1
-   SessOpen       119.xxx.xx.186 53778 :80 10.xx.xx.7 80 1555407000.057236 22
-   Link           req 2 rxreq
-   VSL            flush
-   End            synth

*   << Request  >> 2         
-   Begin          req 1 rxreq
-   Timestamp      Start: 1555407000.058357 0.000000 0.000000
-   Timestamp      Req: 1555407000.058357 0.000000 0.000000
-   ReqStart       119.xxx.xx.186 53778
-   ReqMethod      GET
-   ReqURL         /site1/index.html
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 35.xx.xx.27
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      Upgrade-Insecure-Requests: 1
-   ReqHeader      User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,da;q=0.7
-   ReqHeader      Via: HTTP/1.1 forward.http.proxy:3128
-   ReqHeader      Connection: keep-alive
-   VCL_call       RECV
-   VSL            flush
-   End            synth

Log abandoned
Log reacquired

```
i have commented out the ips for security reasons.

**Comment by gquintard** [comment]
doesn't look like a bug. It's just that you have so much transaction that `varnishlog` can't keep up.

Please check the support channels (https://varnish-cache.org/support/index.html) to get help fixing this.

I'll close this as we only use github issues for bugs.
