### ISSUE TITLE
New release (for varnish 6.2+) anytime soon?

### ISSUE THREAD

**Issue by yjhouzz** [varnish/libvmod-digest#38]
Hi,

First, we've been using this module in our production setup and it works really well. Thank you for such a nice module.

We're currently using varnish 6.1.1 and I thought maybe it's time to upgrade, but then I found that the latest release (1.0.2) wouldn't work with varnish 6.2 and above.  It looks like the issue is already fixed in master branch - so is there any plan to create a new release? 😄 

Thanks!

**Comment by gquintard** [comment]
no plans for a release soon, but https://github.com/varnish/libvmod-digest/tree/6.2 should work for you
