### ISSUE TITLE
Optionally return hash_*() and hmac_*() functions as base64 encoded values

### ISSUE THREAD

**Issue by ericbuehl** [varnish/libvmod-digest#4]
As far as I can tell the only format returned by the various digest methods is a hex encoded string.  Is it easy to retrieve a base64 encoded version of the same data?  Perhaps either:

a) an additional parameter to each hash/hmac function that indicates the desired string format

-- or --

b) a new set hex/base64 util functions

**Comment by rezan** [comment]
Completed, master only. Added base64*_hex() functions to decode the hex string into the raw binary form before base64 encoding.
