### ISSUE TITLE
WS_ReserveAll Error

### ISSUE THREAD

**Issue by isvogor-foi** [varnish/libvmod-digest#42]
When trying to make on Ubuntu 20.04 / Debian Buster (4.19.208-1):

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -Werror -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c: In function 'vmod_base64_generic':
vmod_digest.c:351:6: error: implicit declaration of function 'WS_ReserveAll'; did you mean 'WS_Reserve'? [-Werror=implicit-function-declaration]
  351 |  u = WS_ReserveAll(ctx->ws);
      |      ^~~~~~~~~~~`

**Comment by daghf** [comment]
Hi

This VMOD targets the releases listed under https://varnish-cache.org/releases/index.html. All releases not listed there are end of life and thus not supported.

Recommended packages would be the LTS packages, found here: https://packagecloud.io/varnishcache/varnish60lts/install#manual-deb

`WS_Reserve` had a rather brittle and error-prone interface, and was deprecated and fully replaced by `WS_ReserveAll` in our 6.3.0 release. This change was also backported to 6.0-LTS.
